[theme]
# Archon-inspired dark theme with neon accents
base = "dark"
primaryColor = "#E91E63"  # Neon pink
backgroundColor = "#0E0E0E"  # Pure black
secondaryBackgroundColor = "#1A1A1A"  # Dark gray
textColor = "#FFFFFF"  # White
font = "monospace"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

